---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: flaskmysql
spec: {}
status: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: flaskapi-secrets
  namespace: flaskmysql
type: Opaque
data:
  db_root_password: "U2VuaGElIzEyMw=="
  db_flask_password: "Zmxhc2twYXNz"